
services:
  app:
    build: .                
    image: sgti-app
    container_name: cake_app
    restart: no
    ports:
      - "8080:80"           
    volumes:
      - .:/var/www/html     
    depends_on:
      - db                  
# Verificar configuração de timezone do banco de dados para salvar no formato americano
  db:
    image: postgres:13-alpine
    container_name: cake_db
    restart: no
    environment:
      POSTGRES_DB: cake_db
      POSTGRES_USER: cake_user
      POSTGRES_PASSWORD: cake_password
    ports: 
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data: